/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DoshaRouteImport } from './routes/dosha'
import { Route as DoshaQuizRouteImport } from './routes/dosha-quiz'
import { Route as NutritionPlanRouteImport } from './routes/nutrition-plan'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SwasthyaRouteImport } from './routes/swasthya'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DoshaRoute = DoshaRouteImport.update({
  id: '/dosha',
  path: '/dosha',
  getParentRoute: () => rootRouteImport,
} as any)
const DoshaQuizRoute = DoshaQuizRouteImport.update({
  id: '/dosha-quiz',
  path: '/dosha-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionPlanRoute = NutritionPlanRouteImport.update({
  id: '/nutrition-plan',
  path: '/nutrition-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SwasthyaRoute = SwasthyaRouteImport.update({
  id: '/swasthya',
  path: '/swasthya',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/dosha': typeof DoshaRoute
  '/dosha-quiz': typeof DoshaQuizRoute
  '/nutrition-plan': typeof NutritionPlanRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/swasthya': typeof SwasthyaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/dosha': typeof DoshaRoute
  '/dosha-quiz': typeof DoshaQuizRoute
  '/nutrition-plan': typeof NutritionPlanRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/swasthya': typeof SwasthyaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/dosha': typeof DoshaRoute
  '/dosha-quiz': typeof DoshaQuizRoute
  '/nutrition-plan': typeof NutritionPlanRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/swasthya': typeof SwasthyaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dosha'
    | '/dosha-quiz'
    | '/nutrition-plan'
    | '/onboarding'
    | '/profile'
    | '/swasthya'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dosha'
    | '/dosha-quiz'
    | '/nutrition-plan'
    | '/onboarding'
    | '/profile'
    | '/swasthya'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dosha'
    | '/dosha-quiz'
    | '/nutrition-plan'
    | '/onboarding'
    | '/profile'
    | '/swasthya'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DoshaRoute: typeof DoshaRoute
  DoshaQuizRoute: typeof DoshaQuizRoute
  NutritionPlanRoute: typeof NutritionPlanRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  SwasthyaRoute: typeof SwasthyaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dosha': {
      id: '/dosha'
      path: '/dosha'
      fullPath: '/dosha'
      preLoaderRoute: typeof DoshaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dosha-quiz': {
      id: '/dosha-quiz'
      path: '/dosha-quiz'
      fullPath: '/dosha-quiz'
      preLoaderRoute: typeof DoshaQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition-plan': {
      id: '/nutrition-plan'
      path: '/nutrition-plan'
      fullPath: '/nutrition-plan'
      preLoaderRoute: typeof NutritionPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swasthya': {
      id: '/swasthya'
      path: '/swasthya'
      fullPath: '/swasthya'
      preLoaderRoute: typeof SwasthyaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DoshaRoute: DoshaRoute,
  DoshaQuizRoute: DoshaQuizRoute,
  NutritionPlanRoute: NutritionPlanRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  SwasthyaRoute: SwasthyaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
